#!/usr/bin/env bash

# Opens the GitHub page for a repo/branch in your browser.
# https://github.com/paulirish/git-open/
#
# git open
# git open [remote] [branch]


# are we in a git repo?
git rev-parse --is-inside-work-tree &>/dev/null

if [[ $? != 0 ]]; then
  echo "Not a git repository." 1>&2
  exit 1
fi

# assume origin if not provided
# fallback to upstream if neither is present.
remote="origin"

remote_url="remote.${remote}.url"

giturl=$(git config --get "$remote_url")
if [ -z "$giturl" ]; then
  echo "$remote_url not set." 1>&2
  exit 1
fi

if [ -n "$1" ]; then
  commit=$1
else
  echo "'git open' expect commit sha1"
  exit 1
fi

# URL normalization
# GitHub
if grep -q github <<<$giturl; then
  giturl=${giturl/git\@/https://}
  giturl=${giturl/com\:/com/}
  giturl=${giturl/co\:/co/}

  # handle SSH protocol (links like ssh://git@github.com/user/repo)
  giturl=${giturl/#ssh\:\/\/git\@/https://}
fi
giturl=${giturl%\.git}

giturl="${giturl}/commit/${commit}"

# get current open browser command
case $( uname -s ) in
  Darwin)  open=open;;
  MINGW*)  open=start;;
  CYGWIN*) open=cygstart;;
  MSYS*)   open="powershell.exe –NoProfile Start";;
  *)       open=${BROWSER:-xdg-open};;
esac

# open it in a browser
$open "$giturl" &> /dev/null
exit $?
