#!/usr/bin/env bash

xcode-select --install

./brewfiles
./install_bashit
./install_brew
./install_vundle


ln -sf $PWD/gitignore_global $HOME/.gitignore_global
ln -sfn $PWD/vim $HOME/.vim
ln -sf $PWD/vimrc $HOME/.vimrc
ln -sf $PWD/bash_profile $HOME/.bash_profile
ln -sf $PWD/gemrc $HOME/.gemrc
ln -sf $PWD/git-open /usr/local/bin/git-open
ln -sf $PWD/tmux.conf $HOME/.tmux.conf
ln -sf $PWD/bash_functions $HOME/

# readline problem
if [ -e $HOME/.rbenv/plugins/rbenv-readline ]
then
  echo rbenv-readline is already installed
else
  git clone git://github.com/tpope/rbenv-readline.git \
      $HOME/.rbenv/plugins/rbenv-readline
fi

# setup git diff-highlight
git config --global pager.log 'diff-highlight | less'
git config --global pager.show 'diff-highlight | less'
git config --global pager.diff 'diff-highlight | less'
git config --global interactive.diffFilter diff-highlight
