#!/usr/bin/env bash

ln -sf $PWD/gitignore_global ~/.gitignore_global
ln -sfn $PWD/vim ~/.vim
ln -sf $PWD/vimrc ~/.vimrc
ln -sf $PWD/bash_profile ~/.bash_profile
ln -sf $PWD/gemrc ~/.gemrc

# readline problem
if [ -e ~/.rbenv/plugins/rbenv-readline ]
then
  echo rbenv-readline is already installed
else
  git clone git://github.com/tpope/rbenv-readline.git \
      ~/.rbenv/plugins/rbenv-readline
fi
